### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by mote0230** [AbdulYadi/pgadmin3#1]
Hello, would it be possible to provide a binary for windows?

**Comment by AbdulYadi** [comment]
I do not have Windows installed on my laptop. Please, try build as guided in Windows section in INSTALL file.

**Comment by forrest79** [comment]
Hi, I also want to have Windows binaries and I tried to build it and failed with it. But later, I found this repository https://github.com/levinsv/pgadmin3. There is also updated pgAdmin III for PG12 and it's already builded for Windows.

**Comment by josesydor** [comment]
https://github.com/levinsv/pgadmin3 is the one I've been using so far, but I'd love to see yours compiled to Windows...

**Comment by forrest79** [comment]
I agree... In levinsv fork, there're many improvements, that I don't like. I tried to compile Windows binaries, but I failed, INSTALL guide is old for Windows and I'm not experienced in C++ coding for Windows :-(

**Comment by josesydor** [comment]
Oh cool! Thank you very much, gonna definitely check it out...
