### ISSUE TITLE
Works nice on Debian 10 - compile steps

### ISSUE THREAD

**Issue by scorninpc** [AbdulYadi/pgadmin3#4]
I'm opening this issue to thanks this fork, works fine on Debian 10

Install dependencies
``` 
$ sudo apt-get install libwxgtk3.0 libxml2-dev libxslt-dev libcrypto++-dev libssl-dev postgresql-server-dev-11
```

Build
```
$ ./configure --prefix=/opt/pgadmin3bigsql --with-libgcrypt CFLAGS=-fPIC CXXFLAGS=-fPIC --with-wx-version=3.0
$ make; sudo make install
```

Run
```
$ /opt/pgadmin3bigsql/bin/pgadmin3
```

**Comment by crispond** [comment]
Thanks Bruno and thanks Abdul.  I got it to work on Ubuntu with:

sudo apt install postgresql-server-dev-12
./configure --with-pgsql=/usr/lib/postgresql/12 --with-libgcrypt CFLAGS=-fPIC CXXFLAGS=-fPIC --with-wx-version=3.0
make
sudo make install

pgAdmin4 is a nightmare.  This is a lifesaver.

**Comment by scorninpc** [comment]
Closing just to create reference =)

**Comment by erkinsergey** [comment]
I'll also add to help 
https://github.com/firnsy/yubipam/issues/1#issuecomment-5765929

**Comment by DanoPlurana** [comment]
When i go with the configure command it gets stuck at "checking for strchr... yes" 
Does any of you had this problem?

Thanks in advance
